<?php require('template/header.phtml') ?>





<h1 class="mainText">Smart Meters</h1>

<div class="container">
    <div class="row"">
        <div class="col-lg-6">
            <div class="text-center"
                <p>
                Smart Meter laboratories are focusing on the maximisation of energy efficiency and cost savings.
                The current project that the SMSH laboratory has been working on is the interconnection between
                Smart Meter tech with smart home tech.
                </p>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="text-center"
            <img src="images/thermometer.gif"/>
            </div>
    </div>
</div>











<?php require('template/footer.phtml') ?>
